import React from 'react';
import { Text } from 'react-native';

let quotes = `BE THE REASON SOMEONE BELIEVES IN GOOD PEOPLE.
I CANCEL PLANS TO SPEND TIME WITH ME.
STAY KIND.ITS MAKES YOU BEAUTIFUL.
SOME MOUNTAIN YOU HAVE TO CLIMB BY YOURSELF.
KEEP GOING EVEN THOUGH IT'S TAKING LONGER THAN EXPECTED.
APPRECIATE THOSE WHO DON'T GIVE UP ON YOU.
MAKE GRATITTUDE A HABIT.
KEEP UP THAT HUSTLE.
GOD BLESS THE WOMEN THAT CHASES NOBODY, NEED NO VALIDATION AND MINDS HER OWN.
EVERY ACT OF KINDNESS IS CHARITY.
WHAT YOURS WILL ALWAYS FIND YOU.
I LIKE TO HANG OUT WITH PEOPLE WHO MAKES ME FORGET TO LOOK AT MY PHONE.
EVERYTHING WILL FALL INTO PLACE.
LIFE IS TOO SHORT TO BE NORMAL..........STAY WEIRD....
YOU ARE NOT RESPONSIBLE FOR FULFILLING THE EXPECTATION OF OTHER.
LETTING GO, IS ALSO FREEING UP THE SPACE.
YOU'RE NOT SELFISH FOR WANTING TO BE TREATED WELL.
GOOD THINGS TAKE TIME.
THEY FOUGHT,THEY BURIED US, THEY DIDNOT KNOW WE WERE SEEDS!
PLAY THROUGH PAIN.
IF YOU REALLY WANT TO DO SOMETHING, YOU'LL FIND A WAY. IF YOU DON'T, YOU WILL FIND AN EXCUSE.
TAKE IT DAY BY DAY, DON'T STRESS TOO MUCH ABOUT TOMORROW.
SELF DISCIPLINE IS EVERYTHING.
SPEAK THE TRUTH. EVEN IF IT HURTS YOU OR ME.
BE CAREFREE, NOT CARELESS.
HEAL FROM THINGS THAT YOU NEVER HEARD A SORRY FOR.
YOU'RE ALLOWED TO PACE YOUR SELF.
HOW ARE YOU FEELING TODAY?
IF YOU JUDGE PEOPLE, YOU HAVE NO TIME TO LOVE THEM...
PEOPLE WITH GOOD HEARTS HAVE A GLOW.
PEOPLE WHO SHOW YOU NEW MUSIC ARE IMPORTANT.
YOU'RE ALLOWED TO PACE YOUR SELF.
RELAX, YOU'RE DOING WELL TODAY.
LIVING WELL IS THE BEST REVENGE.
3 HOURS FEELS LIKE 10 MINUTES WITH THE RIGHT PERSON.
ITS ALL WORKS OUT, TRUST YOURSELF.
BE THE ENERGY YOU WANT TO ATTRACT.
PATIENCE IS KEY.
PUSH YOURSELF OUT OF YOUR COMFORT ZONE.
LIFE IS BETTER WHEN YOU ARE SMILING.
BE THANKFUL FOR EVERY DAY OF LIFE.
KINDNESS.IT COST NOTHING.BUT IT MEANS EVERYTHING.
WHATEVER IS GOOD FOR YOUR SOUL, DO THAT.
CHOOSE SOMEONE WHO MOTIVATES YOU.
SURROUND YOURSELF WITH PEOPLE WHO MAKE YOU BETTER.
LIFE IS TOO SHORT TO STAY BROKE.
CONFIDENSE IS ALL YOU NEED.
FILL YOUR LIFE WITH EXPERIENCE.
IF YOU'VE NEVER LOST YOUR MIND, YOU'VE NEVER FOLLOWED YOUR HEART.
YOU ARE STRONGER THAN YOU THINK.
WHEN YOU CAN'T FIND THE SUNSHINE, MAKE YOUR OWN SUNSHINE.
YOU NEED YOU,MORE THAN YOU NEED THEM. TRUST ME.
SURROUND YOURSELF WITH PEOPLE WHO SUPPORT YOU & HELP YOU UP.
PLANT SEEDS. BE PATIENT. YOU CAN'T FAKE GROWTH.
REMEMBER THE DAYS YOU PRAYED FOR THE THINGS YOU HAVE NOW.
I THINK PEOPLE FORGET THAT SOMETIMES THE PERSON WHO TRIES TO FIX EVERYONE NEEDS FIXING TOO.
THIS TIME NEXT YEAR YOU'RE GOING TO BE IN SUCH AN AMAZING PLACE IN YOUR LIFE
YOU'VE SURVIVED SO MUCH.
NEVER APOLOGIZE FOR WHO YOU ARE.
DON'T BE AFRAID TO MAKE YOURSLEF A PRIORITY.
YOU DESERVED TO BE A LOT HAPPIER THAN YOU ARE.
SLOW PROGRESS IS STILL PROGRESS.
NOT EVERYONE LIKES YOU, BUT NOT EVERYONE MATTERS.
YOU WILL BE HAPPY AGAIN.
PEOPLE WHO MAKE YOU FEEL BETTER ABOUT YOUSELF WHEN U R SAD R SO IMPORTANT.
FORGIVENESS IS THE BEST FORM OF LOVE.
SOMETIME IN LIFE YOU JUST NEED A HUG.
NEVER STOP BEING A GOOD PERSON BECAUSE OF BAD PEOPLE.
CHOOSE PEOPLE WHO CHOOSE YOU!
"TRUST YOUR INSTINCT "
HAPPINESS IS ONLY REAL, WHEN SHARED.
IN LIFE NOT NECESSARILY TO BE STRONG BUT TO FEEL STRONG!
DON'T WAIT LIFE GOES FASTER THAN YOU THINK.
YOU EITHER RUN FROM THINGS OR FACE THEM.
NO BAD VIBES
BE DIFFERENT.
WE ONLY LIVE ONCE, WRONG WE ONLY DIE ONCE. WE LIVE EVERYDAY!
STEPPING OUT OF THE COMFORT ZONE AND TRYING NEW THINGS IS BEST WAY TO GROW!
HAPPINESS COMES IN WAVES, IT'LL FIND YOU AGAIN.
A PERSON IS UNSTOPPABLE ONCE THEY REALIZE THEY DESERVE BETTER.
YOU'RE GETTING SO MANY SIGNS. TRUST IT.
I CANCEL PLANS TO SPEND TIME WITH ME.
OF COURSE YOU'LL MAKE MISTAKE BUT THE BIGGEST ONE WOULD BE NOT TO TRY!
STRONG WOMEN STILL NEED THIER HANDS HELD.
SPEND TIME WITH PEOPLE WHO ARE GOOD FOR YOUR MENTAL HEALTH.
A 'FRESH START' ISNT A PLACE. IT'S A MINDSET.
IF YOU WANT TO FLY, GIVE UP EVERYTHING THATS WEIGHS YOU DOWN.
IF YOU ARE GOOD AT SOMETHING, NEVER DO IT FOR FREE.
THE STRONGEST THING A MAN CAN DO IS CRY!
IF YOU HAVE POWER TO MAKE SOMEONE HAPPY, DO IT. THE WORLD NEED MORE OF THAT.
NEVER REGRET ANYTHING THAT MADE YOU SMILE.
DIE WITH MEMORIES, NOT DREAMS.
TOUGH TIMES NEVER LAST BUT TOUGH PEOPLE DO.
BE SO GOOD THEY CAN’T IGNORE YOU.
YESTERDAY YOU SAID TOMORROW. JUST DO IT.
I DONT NEED EASY, JUST NEED POSSIBLE.
TRY TO BE A RAINBOW IN SOMEONE’S CLOUD.
HAPPINESS DEPENDS UPON OURSELVES.
IF THE WORLD WAS BLIND HOW MANY PEOPLE WOULD YOU IMPRESS?
SMILE! HAPPINESS LOOKS GORGEOUS ON YOU.
SMILLING FACE IS A BEAUTIFUL FACE.
A SMILE IS BEST MAKEUP ANY GIRL CAN WEAR.
SMILE, IT'S FREE THERAPY.
YOU ARE POWERFUL. BRILLIANT AND BRAVE.
NO PERSON HAS THE RIGHT TO RAIN ON YOUR DREAMS.
DON'T STOP UNTILL YOU'RE PROUD.
IT ALWAYS SEEMS IMPOSSIBLE UNTIL IT IS DONE.
IF OPPORTUNITY DOESN’T KNOCK, BUILD A DOOR.
IT MAKES A BIG DIFFERENCE IN YOUR LIFE WHEN YOU STAY POSITIVE.
YOU ARE NEVER TOO OLD TO SET ANOTHER GOAL OR DREAM A NEW DREAM.
KEEP YOUR FACE TO THE SUNSHINE AND YOU CANNOT SEE A SHADOW.
THE ONLY TIME YOU FAIL IS WHEN YOU FALL DOWN AND STAY DOWN.
ONLY SURROUND YOURSELF WITH PEOPLE WHO WILL LIFT YOU HIGHER!
HAPPINESS IS THE ONLY THING THAT MULTIPLIES WHEN YOU SHARE IT.
YOU'RE BRAVER THAN YOU BELIEVE,STRONGER THAN YOU SEEM,SMARTER THAN YOU THINK.
BE SO HAPPY THAT, WHEN OTHER PEOPLE LOOK AT YOU, THEY BECOME HAPPY TOO.
WHEN WOMEN SUPPORT EACH OTHER, INCREDIBLE THINGS HAPPEN.
IF YOU WANT SOMETHING SAID, ASK A MAN; IF YOU WANT SOMETHING DONE, ASK A WOMAN.
YOU ARE ART. CREATE YOURSELF OVER AND OVER.
LOVE IS NOT ABOUT OWNERSHIP.
A PASSIONATE WOMEN IS WORTH THE CHAOS!
SWEET REVENGE IS SELF GROWTH.
TRAIN YOURSELF TO TAKE NOTHING PERSONNALY.
WHEN YOU ARE ANGRY, BE SILENT.
'YOU LOOK SO MUCH HAPPIER' IS THE BEST EVER COMPLIMENT.
DAMAGED PEOPLE ARE DANGEROUS. THEY KNOW THEY CAN SURVIVE.
IT TAKE A LOT TO STILL BELIEVE IN PEOPLE.
YOUR GRANDMOTHER'S PRAYERS ARE STILL PROTECTING YOU.
NOTICE THE PEOPLE WHO MAKE AN EFFORT TO STAY IN YOUR LIFE.
NEVER RUN BACK TO WHAT BROKE YOU.
POSITIVE SELF TALK IS SO IMPORTANT.
BE THE REASON SOMEONE BELIEVES IN THE GOODNESS OF PEOPLE.
SILENCE IS ALSO CONVERSATION.
HAVING A SOFT HEART IN A CRUEL WORLD IS COURAGE, NOT WEAKNESS.
THE ONE WHO FALLS AND GETS UP IS SO MUCH STRONGER THAN THE ONE WHO NEVER FELL.
FORM IS TEMPORARY BUT CLASS IS PERMANENT.
SURROUND YOURSELF WITH PEOPLE THAT PUSH YOU TO DO BETTER.
PLANT SEEDS. BE PATIENT. YOU CANNOT FAKE GROWTH.
DON'T UNDERESTIMATE A STRANGERS ABILITY TO TEACH YOU SOMETHING NEW.
IT'S OKEY TO BE KIND WITHOUT EXPECTING KINDNESS IN RETURN.
YOU HAVE SURVIVED A LOT OF THINGS AND JUST LIKE THEM, YOU WILL SURVIVE THIS.
BE A PRIVATE PERSON. LIVE PEACEFULLY.
BEING LONELY DOES'T MEAN YOU'RE UNLOVED.
BE LOYAL BEHIND MY BACK.
MAKE YOUR MENTAL HEALTH A PRIORITY.
MAKE PEACE WITH YOUR MISTAKES AND LET IT GO.
BEING IN SOMEONE’S PRAYERS IS THE PUREST FORM OF LOVE.
BE STRONG ENOUGH TO FORGIVE WITHOUT HEARING AN APOLOGY.
A GOOD LAUGH AND LONG SLEEP ARE THE TWO BEST CURE FOR ANYTHING.
OVER THINKING KILLS YOUR HAPPINESS.
FRIENDS SUPPORT FRIENDS
THE MOST BEAUTIFUL PEOPLE ARE THOSE WITH PASSION IN THEIR EYES AND STRENGTH IN THEIR SOUL.
I'LL NEVER GET TIRED OF ASKING GOD TO GUIDE ME.
TAKE CARE OF PEOPLE WHO TAKE CARE OF YOU.
SOMEONE ELSE IS PRAYING FOR THE THING YOU TAKE FOR GRANTED.
NEVER MAKE ANYONE ELSE RESPONSIBLE FOR YOUR HAPPINESS.
INNER PEACE IS THE NEW SUCCESS.
SPEAK GOOD OR REMAIN SILENT.
ANYTHING THAT COSTS YOU YOUR INNNER PEACE IS TOO EXPENSIVE.
I WATER YOU, YOU WATER ME; WE GROW TOGETHER.
YOU CAN'T LIE TO YOUR SOUL.
YOU ATTRACT WHAT YOU ARE READY FOR.
POSITIVE SELF TALK IS SO IMPORTANT.
YOU GET WHAT YOU GIVE.
A PERSON WHO IS NICE TO YOU, BUT RUDE TO THE WAITER, IS NOT A NICE PERSON.
CONFIDENSE IS NOT THEY WILL LIKE ME, CONFIDENSE IS I'LL BE FINE IF THEY DON'T.
IF YOU ARE TIRED LEARN TO REST,NOT TO QUIT.
SILENCE IS AlSO CONVERSATION.
WHAT MAKES YOU HAPPY DOES NOT NEED APPROVAL FROM SOMEONE ELSE.
YOUR BLESSING ARE BIGGER THAN WHATS STRESSING YOU OUT.
THE RIGHT PEOPLE HELP YOU BREATHE LIGHTER, DEEPER AND EASIER.
SAVE YOUR HEART FOR SOMEONE WHO CARES.
WHEN YOU ARE ANGRY, BE SILENT.
YOU GET WHAT YOU GIVE.
ATTRACT THEM BY THE WAY YOU LIVE.
THE BEAUTY YOU SEE IN ME IS REFLECTION OF YOU.
BUILD IN SILENCE AND MOVE IN SILENCE.
JUST LIKE THE MOON WE GO THROUGH PHASES.
DO WHAT MAKES YOU FEEL FREE.`.split('\n');

export default class Quote extends React.Component {

  getQuote() {
    let q = quotes[Math.floor(Math.random() * quotes.length)].toLowerCase();
    q = '" ' + q.charAt(0).toUpperCase() + q.slice(1) + ' "';
    return q;
  }

  render() {
    return (
      <Text style={{ color: '#888', fontSize: 16, padding: '5%', fontStyle: 'italic', fontFamily: 'serif', textAlign: 'center' }}>
        {this.getQuote()}
      </Text>
    );
  }
}
